[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
startup_timeout_sec = 60

[mcp_servers.next_devtools]
command = "npx.cmd"
args = ["-y", "next-devtools-mcp@0.4.0"]
startup_timeout_sec = 60

[mcp_servers.playwright]
command = "npx.cmd"
args = ["-y", "@playwright/mcp@0.0.79", "--isolated"]
startup_timeout_sec = 60

[mcp_servers.chrome_devtools]
command = "npx.cmd"
args = ["-y", "chrome-devtools-mcp@1.7.0", "--isolated", "--no-usage-statistics"]
startup_timeout_sec = 60
